{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyO3nlZRFUfcKfUMubuvVM2M",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/MDankloff/Cluster-Bias-Disco/blob/main/MLGymTryOut.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Installation instructions"
      ],
      "metadata": {
        "id": "C3PJsmc7mXza"
      }
    },
    {
      "source": [
        "#!rm -rf ml-fairness-gym"
      ],
      "cell_type": "code",
      "metadata": {
        "id": "OXq3WsCrci4B"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "source": [
        "!git clone https://github.com/google/ml-fairness-gym && \\\n",
        "cd /content/ml-fairness-gym && \\\n",
        "sed -i 's/sklearn/scikit-learn/' requirements.txt"
      ],
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "2UJzVhswcIea",
        "outputId": "b6b34623-4482-44a0-8be2-a69b41c544b6"
      },
      "execution_count": 12,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Cloning into 'ml-fairness-gym'...\n",
            "remote: Enumerating objects: 534, done.\u001b[K\n",
            "remote: Counting objects: 100% (117/117), done.\u001b[K\n",
            "remote: Compressing objects: 100% (115/115), done.\u001b[K\n",
            "remote: Total 534 (delta 19), reused 22 (delta 2), pack-reused 417 (from 1)\u001b[K\n",
            "Receiving objects: 100% (534/534), 7.29 MiB | 9.87 MiB/s, done.\n",
            "Resolving deltas: 100% (263/263), done.\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#downgrade setuptools to fix compatability issues for gym == 0.19.0 with newer versions of setuptools\n",
        "!pip install setuptools==57.5.0"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "mdbXpUOZzEFh",
        "outputId": "a804b137-5835-4fae-db41-da65ad445f8c"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: setuptools==57.5.0 in /usr/local/lib/python3.10/dist-packages (57.5.0)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#downgrading pip as well\n",
        "!python -m pip install \"pip>=23.0,<24.0\""
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "ver8GjXpzQ6m",
        "outputId": "bafa0a35-52d1-483a-9a3a-cfe4a7715e56"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting pip<24.0,>=23.0\n",
            "  Downloading pip-23.3.2-py3-none-any.whl.metadata (3.5 kB)\n",
            "Downloading pip-23.3.2-py3-none-any.whl (2.1 MB)\n",
            "\u001b[?25l   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m0.0/2.1 MB\u001b[0m \u001b[31m?\u001b[0m eta \u001b[36m-:--:--\u001b[0m\r\u001b[2K   \u001b[91m━━━━━━\u001b[0m\u001b[90m╺\u001b[0m\u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m0.3/2.1 MB\u001b[0m \u001b[31m10.0 MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\r\u001b[2K   \u001b[91m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[91m╸\u001b[0m \u001b[32m2.1/2.1 MB\u001b[0m \u001b[31m40.0 MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\r\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.1/2.1 MB\u001b[0m \u001b[31m29.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: pip\n",
            "  Attempting uninstall: pip\n",
            "    Found existing installation: pip 24.1.2\n",
            "    Uninstalling pip-24.1.2:\n",
            "      Successfully uninstalled pip-24.1.2\n",
            "Successfully installed pip-23.3.2\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#The version gym==0.19.0 has some metadata issues. We'll download the source, extract it, and modify the setup.py file to fix the opencv-python dependency\n",
        "!pip download gym==0.19.0\n",
        "!tar -xzf gym-0.19.0.tar.gz\n",
        "%cd gym-0.19.0\n",
        "!sed -i 's/opencv-python>=3./opencv-python>=3.0.0/' setup.py"
      ],
      "metadata": {
        "collapsed": true,
        "id": "UKZ50OQwzbUa",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "9cb1bd6e-01a9-49b5-a4d8-0982c555749b"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting gym==0.19.0\n",
            "  Downloading gym-0.19.0.tar.gz (1.6 MB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.6/1.6 MB\u001b[0m \u001b[31m8.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "Collecting numpy>=1.18.0 (from gym==0.19.0)\n",
            "  Downloading numpy-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m62.0/62.0 kB\u001b[0m \u001b[31m4.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting cloudpickle<1.7.0,>=1.2.0 (from gym==0.19.0)\n",
            "  Downloading cloudpickle-1.6.0-py3-none-any.whl.metadata (4.3 kB)\n",
            "Downloading cloudpickle-1.6.0-py3-none-any.whl (23 kB)\n",
            "Downloading numpy-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.3 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m16.3/16.3 MB\u001b[0m \u001b[31m53.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hSaved ./gym-0.19.0.tar.gz\n",
            "Saved ./cloudpickle-1.6.0-py3-none-any.whl\n",
            "Saved ./numpy-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl\n",
            "Successfully downloaded gym cloudpickle numpy\n",
            "/content/gym-0.19.0\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#install remaining dependencies from the requirements.txt file\n",
        "!pip install -r /content/ml-fairness-gym/requirements.txt"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "lYD6nwK0yzU8",
        "outputId": "2abcaca6-612d-46f2-8bdd-fc0c09a09795"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from -r /content/ml-fairness-gym/requirements.txt (line 1)) (1.4.0)\n",
            "Collecting atari-py (from -r /content/ml-fairness-gym/requirements.txt (line 2))\n",
            "  Downloading atari-py-0.2.9.tar.gz (540 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m540.6/540.6 kB\u001b[0m \u001b[31m7.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "Requirement already satisfied: attrs in /usr/local/lib/python3.10/dist-packages (from -r /content/ml-fairness-gym/requirements.txt (line 3)) (24.2.0)\n",
            "Requirement already satisfied: dopamine-rl in /usr/local/lib/python3.10/dist-packages (from -r /content/ml-fairness-gym/requirements.txt (line 4)) (4.0.9)\n",
            "Requirement already satisfied: gin-config in /usr/local/lib/python3.10/dist-packages (from -r /content/ml-fairness-gym/requirements.txt (line 5)) (0.5.0)\n",
            "Collecting gym==0.19.0 (from -r /content/ml-fairness-gym/requirements.txt (line 6))\n",
            "  Using cached gym-0.19.0.tar.gz (1.6 MB)\n",
            "  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from -r /content/ml-fairness-gym/requirements.txt (line 7)) (3.8.0)\n",
            "Collecting monty (from -r /content/ml-fairness-gym/requirements.txt (line 8))\n",
            "  Downloading monty-2024.10.21-py3-none-any.whl.metadata (3.6 kB)\n",
            "Requirement already satisfied: more_itertools in /usr/local/lib/python3.10/dist-packages (from -r /content/ml-fairness-gym/requirements.txt (line 9)) (10.5.0)\n",
            "Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from -r /content/ml-fairness-gym/requirements.txt (line 10)) (3.4.2)\n",
            "Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from -r /content/ml-fairness-gym/requirements.txt (line 11)) (1.26.4)\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from -r /content/ml-fairness-gym/requirements.txt (line 12)) (2.2.2)\n",
            "Collecting recsim (from -r /content/ml-fairness-gym/requirements.txt (line 13))\n",
            "  Downloading recsim-0.2.4.tar.gz (65 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m66.0/66.0 kB\u001b[0m \u001b[31m4.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (from -r /content/ml-fairness-gym/requirements.txt (line 14)) (0.13.2)\n",
            "Collecting simplejson (from -r /content/ml-fairness-gym/requirements.txt (line 15))\n",
            "  Downloading simplejson-3.19.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)\n",
            "Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from -r /content/ml-fairness-gym/requirements.txt (line 16)) (1.5.2)\n",
            "Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (from -r /content/ml-fairness-gym/requirements.txt (line 17)) (0.14.4)\n",
            "Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (from -r /content/ml-fairness-gym/requirements.txt (line 18)) (2.17.1)\n",
            "Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from -r /content/ml-fairness-gym/requirements.txt (line 19)) (4.66.6)\n",
            "Collecting cloudpickle<1.7.0,>=1.2.0 (from gym==0.19.0->-r /content/ml-fairness-gym/requirements.txt (line 6))\n",
            "  Using cached cloudpickle-1.6.0-py3-none-any.whl.metadata (4.3 kB)\n",
            "Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from atari-py->-r /content/ml-fairness-gym/requirements.txt (line 2)) (1.16.0)\n",
            "Requirement already satisfied: opencv-python>=3.4.8.29 in /usr/local/lib/python3.10/dist-packages (from dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (4.10.0.84)\n",
            "Requirement already satisfied: flax>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (0.8.5)\n",
            "Requirement already satisfied: jax>=0.1.72 in /usr/local/lib/python3.10/dist-packages (from dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (0.4.33)\n",
            "Requirement already satisfied: jaxlib>=0.1.51 in /usr/local/lib/python3.10/dist-packages (from dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (0.4.33)\n",
            "Requirement already satisfied: Pillow>=7.0.0 in /usr/local/lib/python3.10/dist-packages (from dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (11.0.0)\n",
            "Requirement already satisfied: pygame>=1.9.2 in /usr/local/lib/python3.10/dist-packages (from dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (2.6.1)\n",
            "Requirement already satisfied: tf-slim>=1.0 in /usr/local/lib/python3.10/dist-packages (from dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (1.1.0)\n",
            "Requirement already satisfied: tensorflow-probability>=0.13.0 in /usr/local/lib/python3.10/dist-packages (from dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (0.24.0)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r /content/ml-fairness-gym/requirements.txt (line 7)) (1.3.1)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r /content/ml-fairness-gym/requirements.txt (line 7)) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r /content/ml-fairness-gym/requirements.txt (line 7)) (4.55.0)\n",
            "Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r /content/ml-fairness-gym/requirements.txt (line 7)) (1.4.7)\n",
            "Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r /content/ml-fairness-gym/requirements.txt (line 7)) (24.2)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r /content/ml-fairness-gym/requirements.txt (line 7)) (3.2.0)\n",
            "Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->-r /content/ml-fairness-gym/requirements.txt (line 7)) (2.8.2)\n",
            "Collecting ruamel.yaml (from monty->-r /content/ml-fairness-gym/requirements.txt (line 8))\n",
            "  Downloading ruamel.yaml-0.18.6-py3-none-any.whl.metadata (23 kB)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->-r /content/ml-fairness-gym/requirements.txt (line 12)) (2024.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->-r /content/ml-fairness-gym/requirements.txt (line 12)) (2024.2)\n",
            "Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from recsim->-r /content/ml-fairness-gym/requirements.txt (line 13)) (1.13.1)\n",
            "Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->-r /content/ml-fairness-gym/requirements.txt (line 16)) (1.4.2)\n",
            "Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->-r /content/ml-fairness-gym/requirements.txt (line 16)) (3.5.0)\n",
            "Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.10/dist-packages (from statsmodels->-r /content/ml-fairness-gym/requirements.txt (line 17)) (1.0.1)\n",
            "Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (1.6.3)\n",
            "Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (24.3.25)\n",
            "Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (0.6.0)\n",
            "Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (0.2.0)\n",
            "Requirement already satisfied: h5py>=3.10.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (3.12.1)\n",
            "Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (18.1.1)\n",
            "Requirement already satisfied: ml-dtypes<0.5.0,>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (0.4.1)\n",
            "Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (3.4.0)\n",
            "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (4.25.5)\n",
            "Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (2.32.3)\n",
            "Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (57.5.0)\n",
            "Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (2.5.0)\n",
            "Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (4.12.2)\n",
            "Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (1.16.0)\n",
            "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (1.68.0)\n",
            "Requirement already satisfied: tensorboard<2.18,>=2.17 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (2.17.1)\n",
            "Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (3.5.0)\n",
            "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (0.37.1)\n",
            "Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (0.45.0)\n",
            "Requirement already satisfied: msgpack in /usr/local/lib/python3.10/dist-packages (from flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (1.1.0)\n",
            "Requirement already satisfied: optax in /usr/local/lib/python3.10/dist-packages (from flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (0.2.4)\n",
            "Requirement already satisfied: orbax-checkpoint in /usr/local/lib/python3.10/dist-packages (from flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (0.6.4)\n",
            "Requirement already satisfied: tensorstore in /usr/local/lib/python3.10/dist-packages (from flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (0.1.68)\n",
            "Requirement already satisfied: rich>=11.1 in /usr/local/lib/python3.10/dist-packages (from flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (13.9.4)\n",
            "Requirement already satisfied: PyYAML>=5.4.1 in /usr/local/lib/python3.10/dist-packages (from flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (6.0.2)\n",
            "Requirement already satisfied: namex in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (0.0.8)\n",
            "Requirement already satisfied: optree in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (0.13.1)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (3.4.0)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (2.2.3)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (2024.8.30)\n",
            "Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (3.7)\n",
            "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (0.7.2)\n",
            "Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (3.1.3)\n",
            "Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from tensorflow-probability>=0.13.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (4.4.2)\n",
            "Requirement already satisfied: dm-tree in /usr/local/lib/python3.10/dist-packages (from tensorflow-probability>=0.13.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (0.1.8)\n",
            "Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml->monty->-r /content/ml-fairness-gym/requirements.txt (line 8))\n",
            "  Downloading ruamel.yaml.clib-0.2.12-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.7 kB)\n",
            "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=11.1->flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (3.0.0)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=11.1->flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (2.18.0)\n",
            "Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.18,>=2.17->tensorflow->-r /content/ml-fairness-gym/requirements.txt (line 18)) (3.0.2)\n",
            "Requirement already satisfied: chex>=0.1.87 in /usr/local/lib/python3.10/dist-packages (from optax->flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (0.1.87)\n",
            "Requirement already satisfied: etils[epy] in /usr/local/lib/python3.10/dist-packages (from optax->flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (1.10.0)\n",
            "Requirement already satisfied: nest_asyncio in /usr/local/lib/python3.10/dist-packages (from orbax-checkpoint->flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (1.6.0)\n",
            "Requirement already satisfied: humanize in /usr/local/lib/python3.10/dist-packages (from orbax-checkpoint->flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (4.11.0)\n",
            "Requirement already satisfied: toolz>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from chex>=0.1.87->optax->flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (0.12.1)\n",
            "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=11.1->flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (0.1.2)\n",
            "Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from etils[epath,epy]->orbax-checkpoint->flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (2024.10.0)\n",
            "Requirement already satisfied: importlib_resources in /usr/local/lib/python3.10/dist-packages (from etils[epath,epy]->orbax-checkpoint->flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (6.4.5)\n",
            "Requirement already satisfied: zipp in /usr/local/lib/python3.10/dist-packages (from etils[epath,epy]->orbax-checkpoint->flax>=0.2.0->dopamine-rl->-r /content/ml-fairness-gym/requirements.txt (line 4)) (3.21.0)\n",
            "Downloading monty-2024.10.21-py3-none-any.whl (68 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m68.5/68.5 kB\u001b[0m \u001b[31m5.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading simplejson-3.19.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (137 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m137.9/137.9 kB\u001b[0m \u001b[31m8.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hUsing cached cloudpickle-1.6.0-py3-none-any.whl (23 kB)\n",
            "Downloading ruamel.yaml-0.18.6-py3-none-any.whl (117 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m117.8/117.8 kB\u001b[0m \u001b[31m8.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading ruamel.yaml.clib-0.2.12-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (722 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m722.2/722.2 kB\u001b[0m \u001b[31m13.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hBuilding wheels for collected packages: gym, atari-py, recsim\n",
            "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
            "  \n",
            "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py bdist_wheel\u001b[0m did not run successfully.\n",
            "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
            "  \u001b[31m╰─>\u001b[0m See above for output.\n",
            "  \n",
            "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
            "  Building wheel for gym (setup.py) ... \u001b[?25lerror\n",
            "\u001b[31m  ERROR: Failed building wheel for gym\u001b[0m\u001b[31m\n",
            "\u001b[0m\u001b[?25h  Running setup.py clean for gym\n",
            "  Building wheel for atari-py (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for atari-py: filename=atari_py-0.2.9-cp310-cp310-linux_x86_64.whl size=2870763 sha256=f3cd3fecd015784c4ed94d410575fc10b098a169a9e4acfd0beab57eaf530dbc\n",
            "  Stored in directory: /root/.cache/pip/wheels/75/6f/04/1f3bf5255580101e16ff487564354dddcdd23ec3b43b775b7a\n",
            "  Building wheel for recsim (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for recsim: filename=recsim-0.2.4-py3-none-any.whl size=105525 sha256=f1fb7d5168fda39dfc9f163936a7e14552670e6a0fb5a270555f7288382ed29e\n",
            "  Stored in directory: /root/.cache/pip/wheels/4f/d4/cc/7a58573c6229c78257d5faff372069f52269ca888144c77ed3\n",
            "Successfully built atari-py recsim\n",
            "Failed to build gym\n",
            "\u001b[31mERROR: Could not build wheels for gym, which is required to install pyproject.toml-based projects\u001b[0m\u001b[31m\n",
            "\u001b[0m"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Set up Environment Variable"
      ],
      "metadata": {
        "id": "E6wimZvA0NPl"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#Need to update the PYTHONPATH so that Colab recognize the ml-fairness-gym package:\n",
        "import os\n",
        "os.environ['PYTHONPATH'] = f\"{os.environ.get('PYTHONPATH', '')}:/content/ml-fairness-gym\"\n"
      ],
      "metadata": {
        "id": "llM6qe_w2Hj8"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "!echo $PYTHONPATH"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ljsvfoycx7qZ",
        "outputId": "83625f66-166c-4eb6-ff1f-03873a5a15dd"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/env/python:/content/ml-fairness-gym\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#fix tensorflow compatibility\n",
        "!pip install tensorflow==2.14"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "EYLhp9w01gkX",
        "outputId": "b838ca17-80cc-4aaa-b541-1cb9945a11d0"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting tensorflow==2.14\n",
            "  Downloading tensorflow-2.14.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)\n",
            "Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (1.4.0)\n",
            "Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (1.6.3)\n",
            "Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (24.3.25)\n",
            "Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (0.6.0)\n",
            "Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (0.2.0)\n",
            "Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (3.12.1)\n",
            "Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (18.1.1)\n",
            "Collecting ml-dtypes==0.2.0 (from tensorflow==2.14)\n",
            "  Downloading ml_dtypes-0.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)\n",
            "Requirement already satisfied: numpy>=1.23.5 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (1.26.4)\n",
            "Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (3.4.0)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (24.2)\n",
            "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (4.25.5)\n",
            "Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (57.5.0)\n",
            "Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (1.16.0)\n",
            "Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (2.5.0)\n",
            "Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (4.12.2)\n",
            "Collecting wrapt<1.15,>=1.11.0 (from tensorflow==2.14)\n",
            "  Downloading wrapt-1.14.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)\n",
            "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (0.37.1)\n",
            "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.14) (1.68.0)\n",
            "Collecting tensorboard<2.15,>=2.14 (from tensorflow==2.14)\n",
            "  Downloading tensorboard-2.14.1-py3-none-any.whl.metadata (1.7 kB)\n",
            "Collecting tensorflow-estimator<2.15,>=2.14.0 (from tensorflow==2.14)\n",
            "  Downloading tensorflow_estimator-2.14.0-py2.py3-none-any.whl.metadata (1.3 kB)\n",
            "Collecting keras<2.15,>=2.14.0 (from tensorflow==2.14)\n",
            "  Downloading keras-2.14.0-py3-none-any.whl.metadata (2.4 kB)\n",
            "Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow==2.14) (0.45.0)\n",
            "Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.15,>=2.14->tensorflow==2.14) (2.27.0)\n",
            "Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.15,>=2.14->tensorflow==2.14)\n",
            "  Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)\n",
            "Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.15,>=2.14->tensorflow==2.14) (3.7)\n",
            "Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.15,>=2.14->tensorflow==2.14) (2.32.3)\n",
            "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.15,>=2.14->tensorflow==2.14) (0.7.2)\n",
            "Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.15,>=2.14->tensorflow==2.14) (3.1.3)\n",
            "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow==2.14) (5.5.0)\n",
            "Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow==2.14) (0.4.1)\n",
            "Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow==2.14) (4.9)\n",
            "Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow==2.14) (1.3.1)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow==2.14) (3.4.0)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow==2.14) (3.10)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow==2.14) (2.2.3)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow==2.14) (2024.8.30)\n",
            "Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.15,>=2.14->tensorflow==2.14) (3.0.2)\n",
            "Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow==2.14) (0.6.1)\n",
            "Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow==2.14) (3.2.2)\n",
            "Downloading tensorflow-2.14.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (489.8 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m489.8/489.8 MB\u001b[0m \u001b[31m1.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading ml_dtypes-0.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.0/1.0 MB\u001b[0m \u001b[31m39.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading keras-2.14.0-py3-none-any.whl (1.7 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.7/1.7 MB\u001b[0m \u001b[31m58.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading tensorboard-2.14.1-py3-none-any.whl (5.5 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m5.5/5.5 MB\u001b[0m \u001b[31m66.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading tensorflow_estimator-2.14.0-py2.py3-none-any.whl (440 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m440.7/440.7 kB\u001b[0m \u001b[31m24.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading wrapt-1.14.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (77 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m77.9/77.9 kB\u001b[0m \u001b[31m5.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)\n",
            "Installing collected packages: wrapt, tensorflow-estimator, ml-dtypes, keras, google-auth-oauthlib, tensorboard, tensorflow\n",
            "  Attempting uninstall: wrapt\n",
            "    Found existing installation: wrapt 1.16.0\n",
            "    Uninstalling wrapt-1.16.0:\n",
            "      Successfully uninstalled wrapt-1.16.0\n",
            "  Attempting uninstall: ml-dtypes\n",
            "    Found existing installation: ml-dtypes 0.4.1\n",
            "    Uninstalling ml-dtypes-0.4.1:\n",
            "      Successfully uninstalled ml-dtypes-0.4.1\n",
            "  Attempting uninstall: keras\n",
            "    Found existing installation: keras 3.5.0\n",
            "    Uninstalling keras-3.5.0:\n",
            "      Successfully uninstalled keras-3.5.0\n",
            "  Attempting uninstall: google-auth-oauthlib\n",
            "    Found existing installation: google-auth-oauthlib 1.2.1\n",
            "    Uninstalling google-auth-oauthlib-1.2.1:\n",
            "      Successfully uninstalled google-auth-oauthlib-1.2.1\n",
            "  Attempting uninstall: tensorboard\n",
            "    Found existing installation: tensorboard 2.17.1\n",
            "    Uninstalling tensorboard-2.17.1:\n",
            "      Successfully uninstalled tensorboard-2.17.1\n",
            "  Attempting uninstall: tensorflow\n",
            "    Found existing installation: tensorflow 2.17.1\n",
            "    Uninstalling tensorflow-2.17.1:\n",
            "      Successfully uninstalled tensorflow-2.17.1\n",
            "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
            "tensorstore 0.1.68 requires ml-dtypes>=0.3.1, but you have ml-dtypes 0.2.0 which is incompatible.\n",
            "tf-keras 2.17.0 requires tensorflow<2.18,>=2.17, but you have tensorflow 2.14.0 which is incompatible.\u001b[0m\u001b[31m\n",
            "\u001b[0mSuccessfully installed google-auth-oauthlib-1.0.0 keras-2.14.0 ml-dtypes-0.2.0 tensorboard-2.14.1 tensorflow-2.14.0 tensorflow-estimator-2.14.0 wrapt-1.14.1\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Run the tests"
      ],
      "metadata": {
        "id": "rduKoY2W2cBh"
      }
    },
    {
      "source": [
        "!cd /content/ml-fairness-gym\n",
        "!chmod +x tests.sh\n",
        "!./tests.sh"
      ],
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "collapsed": true,
        "id": "Gwx8RuZAe2US",
        "outputId": "13fbeed5-8482-4d5c-9adb-b219195de8e2"
      },
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Running tests under Python 3.10.12: /usr/bin/python3\n",
            "[ RUN      ] ParamsTest.test_as_array\n",
            "[       OK ] ParamsTest.test_as_array\n",
            "----------------------------------------------------------------------\n",
            "Ran 1 test in 0.000s\n",
            "\n",
            "OK\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/rewards_test.py\", line 22, in <module>\n",
            "    import rewards\n",
            "  File \"/content/ml-fairness-gym/rewards.py\", line 27, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "/usr/local/lib/python3.10/dist-packages/tensorflow/__init__.py:29: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
            "  import distutils as _distutils\n",
            "2024-11-28 13:03:40.728614: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:03:40.793919: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "2024-11-28 13:03:40.794073: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "2024-11-28 13:03:40.794230: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "2024-11-28 13:03:40.810898: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:03:40.811627: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/dtypes.py:35: DeprecationWarning: ml_dtypes.float8_e4m3b11 is deprecated. Use ml_dtypes.float8_e4m3b11fnuz\n",
            "  from tensorflow.tsl.python.lib.core import pywrap_ml_dtypes\n",
            "2024-11-28 13:03:42.266490: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
            "/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/util.py:51: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs; see https://jax.readthedocs.io/en/latest/aot.html. For example, replace xla_computation(f)(*xs) with jit(f).lower(*xs).compiler_ir('hlo'). See CHANGELOG.md for 0.4.30 for more examples.\n",
            "  from jax import xla_computation as _xla_computation\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/experiments/infectious_disease_rl_test.py\", line 24, in <module>\n",
            "    from experiments import infectious_disease_rl\n",
            "  File \"/content/ml-fairness-gym/experiments/infectious_disease_rl.py\", line 29, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "2024-11-28 13:03:46.572019: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:03:46.619686: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "2024-11-28 13:03:46.619750: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "2024-11-28 13:03:46.619798: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "2024-11-28 13:03:46.630197: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:03:46.630500: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2024-11-28 13:03:48.110996: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/experiments/lending_plots_test.py\", line 25, in <module>\n",
            "    from experiments import lending\n",
            "  File \"/content/ml-fairness-gym/experiments/lending.py\", line 24, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/experiments/attention_allocation_experiment_test.py\", line 23, in <module>\n",
            "    from agents import allocation_agents\n",
            "  File \"/content/ml-fairness-gym/agents/allocation_agents.py\", line 28, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/experiments/infectious_disease_test.py\", line 24, in <module>\n",
            "    from experiments import infectious_disease\n",
            "  File \"/content/ml-fairness-gym/experiments/infectious_disease.py\", line 24, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/experiments/lending_test.py\", line 24, in <module>\n",
            "    from experiments import lending\n",
            "  File \"/content/ml-fairness-gym/experiments/lending.py\", line 24, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/experiments/college_admission_test.py\", line 27, in <module>\n",
            "    from experiments import college_admission\n",
            "  File \"/content/ml-fairness-gym/experiments/college_admission.py\", line 25, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "2024-11-28 13:03:54.306600: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:03:54.356408: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "2024-11-28 13:03:54.356471: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "2024-11-28 13:03:54.356524: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "2024-11-28 13:03:54.365527: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:03:54.365885: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2024-11-28 13:03:55.803328: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/experiments/movielens_recs_test.py\", line 26, in <module>\n",
            "    from environments.recommenders import movie_lens_dynamic\n",
            "  File \"/content/ml-fairness-gym/environments/recommenders/movie_lens_dynamic.py\", line 37, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/experiments/college_admission_util_test.py\", line 23, in <module>\n",
            "    import runner_lib\n",
            "  File \"/content/ml-fairness-gym/runner_lib.py\", line 29, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/environments/attention_allocation_test.py\", line 24, in <module>\n",
            "    import test_util\n",
            "  File \"/content/ml-fairness-gym/test_util.py\", line 25, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/environments/template_test.py\", line 23, in <module>\n",
            "    import test_util\n",
            "  File \"/content/ml-fairness-gym/test_util.py\", line 25, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/environments/recommenders/restaurant_toy_recsim_test.py\", line 23, in <module>\n",
            "    import test_util\n",
            "  File \"/content/ml-fairness-gym/test_util.py\", line 25, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "2024-11-28 13:04:01.164811: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:04:01.216621: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "2024-11-28 13:04:01.216693: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "2024-11-28 13:04:01.216759: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "2024-11-28 13:04:01.226364: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:04:01.226696: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2024-11-28 13:04:02.942107: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/environments/recommenders/movie_lens_dynamic_test.py\", line 26, in <module>\n",
            "    import test_util\n",
            "  File \"/content/ml-fairness-gym/test_util.py\", line 25, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Running tests under Python 3.10.12: /usr/bin/python3\n",
            "[ RUN      ] DownloadMovielensTest.test_pandas_bytes_behavior\n",
            "/content/ml-fairness-gym/environments/recommenders/download_movielens_test.py:31: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.\n",
            "  _ = pd.read_csv(f, sep='::', encoding='iso-8859-1')\n",
            "[       OK ] DownloadMovielensTest.test_pandas_bytes_behavior\n",
            "----------------------------------------------------------------------\n",
            "Ran 1 test in 0.012s\n",
            "\n",
            "OK\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/environments/recommenders/recsim_wrapper_test.py\", line 24, in <module>\n",
            "    import test_util\n",
            "  File \"/content/ml-fairness-gym/test_util.py\", line 25, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/environments/infectious_disease_test.py\", line 22, in <module>\n",
            "    import test_util\n",
            "  File \"/content/ml-fairness-gym/test_util.py\", line 25, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/environments/lending_test.py\", line 25, in <module>\n",
            "    import test_util\n",
            "  File \"/content/ml-fairness-gym/test_util.py\", line 25, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/environments/college_admission_test.py\", line 22, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/runner_lib_test.py\", line 22, in <module>\n",
            "    import core  # pylint: disable=unused-import\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/metrics/error_metrics_test.py\", line 23, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/metrics/lending_metrics_test.py\", line 22, in <module>\n",
            "    import rewards\n",
            "  File \"/content/ml-fairness-gym/rewards.py\", line 27, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/metrics/infectious_disease_metrics_test.py\", line 21, in <module>\n",
            "    from environments import infectious_disease\n",
            "  File \"/content/ml-fairness-gym/environments/infectious_disease.py\", line 36, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/metrics/distribution_comparison_metrics_test.py\", line 23, in <module>\n",
            "    import test_util\n",
            "  File \"/content/ml-fairness-gym/test_util.py\", line 25, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/metrics/value_tracking_metrics_test.py\", line 24, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/core_test.py\", line 27, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Running tests under Python 3.10.12: /usr/bin/python3\n",
            "[ RUN      ] GraphTest.test_sampled_graphs_contain_correct_number_of_nodes\n",
            "[       OK ] GraphTest.test_sampled_graphs_contain_correct_number_of_nodes\n",
            "[ RUN      ] GraphTest.test_undirected_space_not_equal_to_directed_space\n",
            "[       OK ] GraphTest.test_undirected_space_not_equal_to_directed_space\n",
            "----------------------------------------------------------------------\n",
            "Ran 2 tests in 0.006s\n",
            "\n",
            "OK\n",
            "Running tests under Python 3.10.12: /usr/bin/python3\n",
            "[ RUN      ] MultinomialTest.test_contains_correct\n",
            "[       OK ] MultinomialTest.test_contains_correct\n",
            "[ RUN      ] MultinomialTest.test_contains_correct_n_in_vector\n",
            "[       OK ] MultinomialTest.test_contains_correct_n_in_vector\n",
            "[ RUN      ] MultinomialTest.test_contains_incorrect_dtype\n",
            "[       OK ] MultinomialTest.test_contains_incorrect_dtype\n",
            "[ RUN      ] MultinomialTest.test_contains_incorrect_length\n",
            "[       OK ] MultinomialTest.test_contains_incorrect_length\n",
            "[ RUN      ] MultinomialTest.test_contains_incorrect_sum\n",
            "[       OK ] MultinomialTest.test_contains_incorrect_sum\n",
            "[ RUN      ] MultinomialTest.test_contains_samples\n",
            "[       OK ] MultinomialTest.test_contains_samples\n",
            "[ RUN      ] MultinomialTest.test_sample_distribution\n",
            "[       OK ] MultinomialTest.test_sample_distribution\n",
            "[ RUN      ] MultinomialTest.test_sample_sum\n",
            "[       OK ] MultinomialTest.test_sample_sum\n",
            "----------------------------------------------------------------------\n",
            "Ran 8 tests in 0.007s\n",
            "\n",
            "OK\n",
            "Running tests under Python 3.10.12: /usr/bin/python3\n",
            "[ RUN      ] BatchTest.test_batches_are_contained_in_space\n",
            "[       OK ] BatchTest.test_batches_are_contained_in_space\n",
            "----------------------------------------------------------------------\n",
            "Ran 1 test in 0.004s\n",
            "\n",
            "OK\n",
            "Running tests under Python 3.10.12: /usr/bin/python3\n",
            "[ RUN      ] MultiDiscreteWithNoneTest.test_base_and_with_none_agree\n",
            "[       OK ] MultiDiscreteWithNoneTest.test_base_and_with_none_agree\n",
            "[ RUN      ] MultiDiscreteWithNoneTest.test_none_can_be_sampled\n",
            "/usr/local/lib/python3.10/dist-packages/gym/utils/seeding.py:41: DeprecationWarning: \u001b[33mWARN: Function `rng.rand(*size)` is marked as deprecated and will be removed in the future. Please use `Generator.random(size)` instead.\u001b[0m\n",
            "  deprecation(\n",
            "[       OK ] MultiDiscreteWithNoneTest.test_none_can_be_sampled\n",
            "[ RUN      ] MultiDiscreteWithNoneTest.test_space_contains_none\n",
            "[       OK ] MultiDiscreteWithNoneTest.test_space_contains_none\n",
            "----------------------------------------------------------------------\n",
            "Ran 3 tests in 0.001s\n",
            "\n",
            "OK\n",
            "2024-11-28 13:04:14.969226: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:04:15.019209: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "2024-11-28 13:04:15.019275: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "2024-11-28 13:04:15.019324: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "2024-11-28 13:04:15.028565: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:04:15.028926: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2024-11-28 13:04:16.913883: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
            "Running tests under Python 3.10.12: /usr/bin/python3\n",
            "[ RUN      ] UtilitiesTest.test_delete_recursively\n",
            "[       OK ] UtilitiesTest.test_delete_recursively\n",
            "[ RUN      ] UtilitiesTest.test_makedirs\n",
            "[       OK ] UtilitiesTest.test_makedirs\n",
            "[ RUN      ] UtilitiesTest.test_read_write_files\n",
            "[       OK ] UtilitiesTest.test_read_write_files\n",
            "----------------------------------------------------------------------\n",
            "Ran 3 tests in 0.003s\n",
            "\n",
            "OK\n",
            "Running tests under Python 3.10.12: /usr/bin/python3\n",
            "[ RUN      ] DistributionsTest.test_bernoulli_returns_proportionally\n",
            "[       OK ] DistributionsTest.test_bernoulli_returns_proportionally\n",
            "[ RUN      ] DistributionsTest.test_constant_returns_the_same_thing\n",
            "[       OK ] DistributionsTest.test_constant_returns_the_same_thing\n",
            "[ RUN      ] DistributionsTest.test_gaussian_has_right_mean_std\n",
            "[       OK ] DistributionsTest.test_gaussian_has_right_mean_std\n",
            "[ RUN      ] DistributionsTest.test_improper_distributions_raise_errors\n",
            "[       OK ] DistributionsTest.test_improper_distributions_raise_errors\n",
            "[ RUN      ] DistributionsTest.test_mixture_returns_components\n",
            "[       OK ] DistributionsTest.test_mixture_returns_components\n",
            "----------------------------------------------------------------------\n",
            "Ran 5 tests in 0.055s\n",
            "\n",
            "OK\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/agents/oracle_lending_agent_test.py\", line 24, in <module>\n",
            "    import rewards\n",
            "  File \"/content/ml-fairness-gym/rewards.py\", line 27, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/agents/infectious_disease_agents_test.py\", line 24, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "2024-11-28 13:04:22.086815: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:04:22.136558: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "2024-11-28 13:04:22.136646: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "2024-11-28 13:04:22.136703: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "2024-11-28 13:04:22.148887: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:04:22.149286: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2024-11-28 13:04:23.600363: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/agents/recommenders/batched_movielens_rnn_agent_test.py\", line 24, in <module>\n",
            "    from agents.recommenders import batched_movielens_rnn_agent\n",
            "  File \"/content/ml-fairness-gym/agents/recommenders/batched_movielens_rnn_agent.py\", line 23, in <module>\n",
            "    from agents.recommenders import rnn_cvar_agent\n",
            "  File \"/content/ml-fairness-gym/agents/recommenders/rnn_cvar_agent.py\", line 20, in <module>\n",
            "    from agents.recommenders import rnn_agent\n",
            "  File \"/content/ml-fairness-gym/agents/recommenders/rnn_agent.py\", line 28, in <module>\n",
            "    import recsim\n",
            "ModuleNotFoundError: No module named 'recsim'\n",
            "2024-11-28 13:04:26.856617: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:04:26.905335: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "2024-11-28 13:04:26.905397: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "2024-11-28 13:04:26.905450: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "2024-11-28 13:04:26.914711: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:04:26.915038: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2024-11-28 13:04:28.399897: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/agents/recommenders/evaluation_test.py\", line 26, in <module>\n",
            "    from agents.recommenders import rnn_cvar_agent\n",
            "  File \"/content/ml-fairness-gym/agents/recommenders/rnn_cvar_agent.py\", line 20, in <module>\n",
            "    from agents.recommenders import rnn_agent\n",
            "  File \"/content/ml-fairness-gym/agents/recommenders/rnn_agent.py\", line 28, in <module>\n",
            "    import recsim\n",
            "ModuleNotFoundError: No module named 'recsim'\n",
            "2024-11-28 13:04:34.250277: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:04:34.304256: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "2024-11-28 13:04:34.304331: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "2024-11-28 13:04:34.304381: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "2024-11-28 13:04:34.314307: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.\n",
            "2024-11-28 13:04:34.314676: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2024-11-28 13:04:35.659882: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/agents/recommenders/model_test.py\", line 20, in <module>\n",
            "    from agents.recommenders import batched_movielens_rnn_agent\n",
            "  File \"/content/ml-fairness-gym/agents/recommenders/batched_movielens_rnn_agent.py\", line 23, in <module>\n",
            "    from agents.recommenders import rnn_cvar_agent\n",
            "  File \"/content/ml-fairness-gym/agents/recommenders/rnn_cvar_agent.py\", line 20, in <module>\n",
            "    from agents.recommenders import rnn_agent\n",
            "  File \"/content/ml-fairness-gym/agents/recommenders/rnn_agent.py\", line 28, in <module>\n",
            "    import recsim\n",
            "ModuleNotFoundError: No module named 'recsim'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/agents/classifier_agents_test.py\", line 26, in <module>\n",
            "    import rewards\n",
            "  File \"/content/ml-fairness-gym/rewards.py\", line 27, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/agents/random_agents_test.py\", line 24, in <module>\n",
            "    import test_util\n",
            "  File \"/content/ml-fairness-gym/test_util.py\", line 25, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/agents/allocation_agents_test.py\", line 24, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"/content/ml-fairness-gym/agents/college_admission_jury_test.py\", line 21, in <module>\n",
            "    import core\n",
            "  File \"/content/ml-fairness-gym/core.py\", line 33, in <module>\n",
            "    import gym.utils.json_utils\n",
            "ModuleNotFoundError: No module named 'gym.utils.json_utils'\n",
            "Running tests under Python 3.10.12: /usr/bin/python3\n",
            "[ RUN      ] ThresholdPoliciesTest.test_convex_hull_roc\n",
            "[       OK ] ThresholdPoliciesTest.test_convex_hull_roc\n",
            "[ RUN      ] ThresholdPoliciesTest.test_equality_of_opportunity_holds\n",
            "[       OK ] ThresholdPoliciesTest.test_equality_of_opportunity_holds\n",
            "[ RUN      ] ThresholdPoliciesTest.test_reward_is_maximized\n",
            "[       OK ] ThresholdPoliciesTest.test_reward_is_maximized\n",
            "[ RUN      ] ThresholdPoliciesTest.test_weighted_single_threshold\n",
            "[       OK ] ThresholdPoliciesTest.test_weighted_single_threshold\n",
            "----------------------------------------------------------------------\n",
            "Ran 4 tests in 13.467s\n",
            "\n",
            "OK\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Run the simulation"
      ],
      "metadata": {
        "id": "CRfSRaP07TQm"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "!cd /content/ml-fairness-gym\n",
        "!ls /content/ml-fairness-gym/experiments/lending_demo.py\n",
        "!python /content/ml-fairness-gym/experiments/lending_demo.py --num_steps=5000"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "lYkWc8bElATA",
        "outputId": "4dc923a1-ea45-4fbe-cbd3-a98106d00207"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/content/ml-fairness-gym/experiments/lending_demo.py\n",
            "  File \"/content/ml-fairness-gym/experiments/lending_demo.py\", line 25\n",
            "    from ml-fairness-gym.agents import threshold_policies\n",
            "           ^\n",
            "SyntaxError: invalid syntax\n"
          ]
        }
      ]
    }
  ]
}